### ISSUE TITLE
Add allocation ID and date to notification. Date Format: 01 Jan 2015

### ISSUE THREAD

**Issue by reneeorser** [chailmis/chailmis-android#110]
High Severity

When allocations are done on the server, it shows up as a message on the home page of the app and displays on the message board without the allocation ID, this means the user must know the allocation ID before he can receive the allocation on the app. Allocation notification should include - allocation number and date of allocation

Egwuma - Notifications - 3/3/2015

**Comment by chai-lmis** [comment]
date format is still year/month/day this should be day/month/year

**Comment by cvaldez519** [comment]
TESTED.  Data is visible from home page with appropriate formatting.
