### ISSUE TITLE
Reports take about 5-10mins to load (are these loading from the server or locally?)

### ISSUE THREAD

**Issue by LakshmiCHAI** [chailmis/chailmis-android#140]
Severity: Medium

**Comment by reneeorser** [comment]
To discuss categorization as feature, not bug.

**Comment by reneeorser** [comment]
Dependent on #130 indirectly

**Comment by reneeorser** [comment]
8 April QA comment: None of the reports load (although the bin card loads quickly but does not correctly identify the “received from/issued to”)

**Comment by cvaldez519** [comment]
TESTED. All reports loaded in a reasonable amount of time. Had one crash or what seemed like a crash during this time, but it was not logged via crashlytics.  Are we swallowing any exceptions?
