### ISSUE TITLE
“Facility Consumption Reports RH1” should be renamed “Daily Facility Consumption Reports” for all categories except for the Family Planning category which should be “Daily Facility Consumption Reports RH1”. The name “Daily Facility Consumption Report  for <category>” should also be displayed at the top of the report page. “Facility Stock Report” should be renamed “Monthly Facility Stock Report”

### ISSUE THREAD

**Issue by LakshmiCHAI** [chailmis/chailmis-android#144]
Severity: Low

**Comment by chai-lmis** [comment]
Rename Family Planning "Facility Consumption Report RH2" to "Monthly Facility Consumption Report RH2"

**Comment by chai-lmis** [comment]
Rename Family Planning "Facility Consumption Report RH2" to "Monthly Facility Consumption Report RH2"
Rename Family Planning "Monthly Facility Stock Report" to "RH RIRF"

**Comment by cvaldez519** [comment]
TESTED. This is working for all reports. Family planning and Vaccines reports are the only exception to this which I believe is the desired behavior.
