### ISSUE TITLE
Reports: Value for commodity balance is cascaded to days in the future, adjust reports to only show values up to the current day - Critical

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#148]

**Comment by reneeorser** [comment]
BUG

**Comment by reneeorser** [comment]
Clarity on whether quantity sent by First Facility is no longer necessary.

**Comment by cvaldez519** [comment]
TESTED. FAILED.   This is working correctly for all reports  except for Monthly Health Facility Devices Report & Monthly Health Facility Vaccines Utilization Report these are still displaying dates in the future.  Moving back to Dev.

**Comment by cvaldez519** [comment]
Can't test this today via the tablet as it is the last day of the month, so all days should be displayed. However, after reviewing the code changes, and unit test updates for this change, it looks like it should be working correctly. I will have to verify this tomorrow.

**Comment by cvaldez519** [comment]
TESTED. FAILED. Both Monthly Health Facility Devices Report & Monthly Health Facility Vaccines Utilization Report are going 1 day into the future. All other reports are working fine.  Do we want to create a new card just for these 2 reports and close this one out?

**Comment by karlwbrown** [comment]
Is this a new bug? If so better to create a new card, referencing this one, and close this one out if the original bug noted here was fixed. Otherwise, keep open and just update the details of the bug itself.

**Comment by cvaldez519** [comment]
it's not a new bug as this one references all reports, but the other reports are fixed except for two, so I was just wondering if we wanted to decompose this one and close out what is done, but leave a card for what isn't

**Comment by karlwbrown** [comment]
I'd say keep it open until it's fixed for all reports... Just update the title to describe the current status of the bug.

**Comment by cvaldez519** [comment]
TESTED. PASSED. Both reports are showing only to the current date.
