### ISSUE TITLE
Make report button size and DropDown item size larger

### ISSUE THREAD

**Issue by LakshmiCHAI** [chailmis/chailmis-android#153]
Buttons for selecting month are very small and difficult to select a specific month, make these bigger

Severity: High

**Comment by reneeorser** [comment]
Duplicate of 145, but high instead of low. Will delete #145

**Comment by chai-lmis** [comment]
can this button be made slightly bigger still (for clumsy fingers like mine)

**Comment by cameotisha** [comment]
- Months and years in the drop down list still appear small to a person who has not used a tablet or smart phone before
Test
- Tried selecting month and year with my thumb and was able to select the required year

Unable to test
------
- When there are many years, how scroll works.
_-Not sure how small the buttons were before. test not conclusive

**Comment by chai-lmis** [comment]
Months and years drop down should be enlarged - large  enough for someone to select the correct month on the first attempt- comfortable

**Comment by cameotisha** [comment]
Tests
-------
- Dropdown list bigger and easier to click
- Column labels have been wrapped and space between each column is now uniform
- Test Result: Passed
