### ISSUE TITLE
Increase speed of selecting Commodities on the fragment (Dialog)

### ISSUE THREAD

**Issue by jobasiimwe** [chailmis/chailmis-android#166]
Selecting/Deselecting commodities is slow

**Comment by jobasiimwe** [comment]
We made some changes to the internal processing of the selection. 
We tested the APK from CI on the Chai-Nigeria tablet and another tablet (Sony Xperia), the App is now un-usually fast. We are waiting for feedback from CHAI Team on this.

**Comment by chai-lmis** [comment]
i still notice a delay when selecting commodities

**Comment by cameotisha** [comment]
Test and Observations
-----
- Based on tests and discussions with Job, the current speed is sufficient and much faster than what what was there before. still have to confirm with the client.
