### ISSUE TITLE
stock out vs low stock alert colouring

### ISSUE THREAD

**Issue by jobasiimwe** [chailmis/chailmis-android#167]
Stock out alert should be red, low stock should be yellow.

**Comment by chai-lmis** [comment]
There is now a colour difference when SOH is 0, however its black, while the low stock is white. It will make logical sense to have low stock as amber/yellow and stock out as red

**Comment by chai-lmis** [comment]
stock out is now red, but low stock is still white, can this be changed to yellow/amber
