### ISSUE TITLE
Auto-update alerts/notifications of HomePage whenever there are changes to Alerts/notifications in the Database

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#170]

**Comment by jobasiimwe** [comment]
When you 1st load the hope page, alerts and notifications have not yet been created in the Database..they are created by a background process
But when you move to any other activity and then return, the home page re-loads and the alerts will be shown
Note: this delay only happens after initial registration.
After that, notifications will always be there when u 1st load the home page…even when u update the app from our private app store, notifications will be there immidiately
