### ISSUE TITLE
When a physical stock count is successfully completed, the next page that comes up is still a physical stock count page, an this go back to the home page after a physical stock count is successfully completed

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#179]

**Comment by jobasiimwe** [comment]
When adjustment reason is Physical count, The app returns to the Home screen...All other reasons return to the adjustmentActivity with the reason cleared.

**Comment by cvaldez519** [comment]
TESTED. When valid value is entered for reason = "physical count" the user is redirected to the home page after submission. When the same type of transaction is performed for any other reason the Adjustment screen is displayed without a reason. 

When a really large number is entered and causes a negative overflow this is allowed on the SOH becomes 0. I think this is a bug and we should not allow a user to enter a number that causes an overflow, but is not necessarily related to this issue so will create a separate ticket for adding this validation.

**Comment by jobasiimwe** [comment]
Thanks Christian, thats a bug
