### ISSUE TITLE
Hide the allocated quantity when receiving from other sources

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#185]

**Comment by cameotisha** [comment]
Tests
-------
Test1
- Selected Receive from Menu
- Selected others from source 
- Selected EM-Child Health, Albendanzole 200mg Tablet X 2
- Only Received Quantity field was visible.
-Test Result: Passed

Test2
- Selected Receive from Menu
- Selected Others from source 
- Selected EM-Child Health, Albendanzole 200mg Tablet X 2
- Only Received Quantity field was visible.
- changed source to LGA/ State CMS
- Allocate Quantity field , Received Quantity Field and Difference Field were all visible
- Test Result: Passed

**Comment by cvaldez519** [comment]
CONFIRMED
