### ISSUE TITLE
When reason for an emergency order is entered before the quantity to order is entered, the validation does not work, as it still asks for a reason for the emergency order to be entered

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#186]

**Comment by cameotisha** [comment]
Test
-------
- Selected Artesunate Injection x 1 entered reason first: Losses, then entered quantity as 50
- selected Rapid Diagnostic Test (RDT) x 1 entered reason first: Expiries, then entered quantity as 60
- clicked submit
- Asked to confirm quantity ordered
- Quantity confirmed
- Order saved successfully
- Navigated back to blank order screen
- Test Result: test passed
